# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/



# Site settings
locale: "en-US"
title: Alicia Vanderpool
subtitle: "Marketing & Design"
name: "Alicia Vanderpool" 
description: >-
  Portfolio Site
url: "https://alivande97.github.io"

# Author Info
author:
  name: "Alicia Vanderpool"
  avatar: "assets/images/prof_pic.jpg"
  bio: "Marketing professional and visual artist."
  location: "Mason, MI"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/wolverineconcepts"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alivande97"

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"
# options: air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/wolverineconcepts"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alivande97"
  since: "2026"

include:
  - _pages
exclude:
  - README.md
  - vendor/
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# The following are excluded automatically
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache